// A curated list of "related" word pairs.
// The crew all receive `common`; the imposter receives `imposter`.
// Words are close enough that the imposter can bluff, but distinct
// enough that careful clues can expose them.
export const WORD_PAIRS = [
  { common: "Coffee", imposter: "Tea" },
  { common: "Pizza", imposter: "Burger" },
  { common: "Dog", imposter: "Cat" },
  { common: "Ocean", imposter: "Lake" },
  { common: "Guitar", imposter: "Violin" },
  { common: "Winter", imposter: "Autumn" },
  { common: "Doctor", imposter: "Nurse" },
  { common: "Airplane", imposter: "Helicopter" },
  { common: "Apple", imposter: "Pear" },
  { common: "Football", imposter: "Rugby" },
  { common: "Sun", imposter: "Moon" },
  { common: "Book", imposter: "Magazine" },
  { common: "River", imposter: "Canal" },
  { common: "Piano", imposter: "Keyboard" },
  { common: "Train", imposter: "Tram" },
  { common: "Lion", imposter: "Tiger" },
  { common: "Beach", imposter: "Desert" },
  { common: "Wine", imposter: "Beer" },
  { common: "Castle", imposter: "Palace" },
  { common: "Snow", imposter: "Rain" },
  { common: "Butterfly", imposter: "Moth" },
  { common: "Chocolate", imposter: "Candy" },
  { common: "Mountain", imposter: "Hill" },
  { common: "Sword", imposter: "Dagger" },
  { common: "Rose", imposter: "Tulip" },
  { common: "Phone", imposter: "Tablet" },
  { common: "Chef", imposter: "Baker" },
  { common: "Diamond", imposter: "Crystal" },
  { common: "Whale", imposter: "Dolphin" },
  { common: "Bicycle", imposter: "Motorcycle" },
  { common: "Teacher", imposter: "Professor" },
  { common: "Cloud", imposter: "Fog" },
  { common: "Honey", imposter: "Syrup" },
  { common: "Forest", imposter: "Jungle" },
  { common: "Painting", imposter: "Sketch" },
  { common: "Rocket", imposter: "Missile" },
  { common: "Volcano", imposter: "Geyser" },
  { common: "Spider", imposter: "Scorpion" },
  { common: "Island", imposter: "Peninsula" },
  { common: "Umbrella", imposter: "Raincoat" },
  { common: "Robot", imposter: "Android" },
  { common: "Pirate", imposter: "Sailor" },
  { common: "Ghost", imposter: "Zombie" },
  { common: "Cake", imposter: "Pie" },
  { common: "Soccer", imposter: "Hockey" },
  { common: "Camera", imposter: "Binoculars" },
  { common: "Bridge", imposter: "Tunnel" },
  { common: "Wolf", imposter: "Fox" },
  { common: "Strawberry", imposter: "Raspberry" },
  { common: "King", imposter: "Emperor" },
];

export function randomWordPair() {
  return WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
}
